### ISSUE TITLE
possibly incorrect use of __CUDA_ARCH__ in Utilities.cuh ?

### ISSUE THREAD

**Issue by cbuchner1** [OrangeOwlSolutions/CUDA-Utilities#1]
**CUDA_ARCH** represents the CUDA compute model in device code.

http://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#virtual-architecture-identification-macro

As there is no Compute 7.0 architecture, I think instead you should be using one or more of these macros to check the actual CUDA toolkit (or NVCC) version at compile time

http://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/#nvcc-identification-macro

Christian

**Comment by cbuchner1** [comment]
Note: Utilities.cu contains the same broken version check.

I would suggest to use this test instead.

#if __CUDACC_VER_MAJOR__ >= 7

**Comment by cbuchner1** [comment]
this would also work

#if defined(__CUDACC__) && (CUDA_VERSION >= 7000)

**Comment by OrangeOwlSolutions** [comment]
Hi Christian,
thank you very much for your notices and comments. We have fixed Utilities.cuh and Utilities.cu according to your last suggestion.
OOS Team
