### ISSUE TITLE
format string warnings in Utilities.cu

### ISSUE THREAD

**Issue by cbuchner1** [OrangeOwlSolutions/CUDA-Utilities#3]
On Ubuntu 16.04 using CUDA toolkit 7.5 I get the following compiler warnings when building Utilities.cu in 64 bit mode:

Utilities.cu: In function ‘void __cusolveSafeCall(cusolverStatus_t, const char_, int)’:
Utilities.cu:78:158: warning: unknown conversion type character ‘N’ in format [-Wformat=]
Utilities.cu:78:158: warning: format ‘%s’ expects argument of type ‘char_’, but argument 4 has type ‘int’ [-Wformat=]
Utilities.cu:78:158: warning: unknown conversion type character ‘N’ in format [-Wformat=]
Utilities.cu:78:158: warning: format ‘%s’ expects argument of type ‘char_’, but argument 5 has type ‘int’ [-Wformat=]
Utilities.cu:78:158: warning: too many arguments for format [-Wformat-extra-args]
Utilities.cu: In function ‘void __cublasSafeCall(cublasStatus_t, const char_, int)’:
Utilities.cu:131:156: warning: unknown conversion type character ‘N’ in format [-Wformat=]
Utilities.cu:131:156: warning: format ‘%s’ expects argument of type ‘char_’, but argument 4 has type ‘int’ [-Wformat=]
Utilities.cu:131:156: warning: unknown conversion type character ‘N’ in format [-Wformat=]
Utilities.cu:131:156: warning: format ‘%s’ expects argument of type ‘char_’, but argument 5 has type ‘int’ [-Wformat=]
Utilities.cu:131:156: warning: too many arguments for format [-Wformat-extra-args]
Utilities.cu: In function ‘void __cusparseSafeCall(cusparseStatus_t, const char_, int)’:
Utilities.cu:236:160: warning: unknown conversion type character ‘N’ in format [-Wformat=]
Utilities.cu:236:160: warning: format ‘%s’ expects argument of type ‘char_’, but argument 4 has type ‘int’ [-Wformat=]
Utilities.cu:236:160: warning: unknown conversion type character ‘N’ in format [-Wformat=]
Utilities.cu:236:160: warning: format ‘%s’ expects argument of type ‘char*’, but argument 5 has type ‘int’ [-Wformat=]
Utilities.cu:236:160: warning: too many arguments for format [-Wformat-extra-args]

This may be worth looking into.

**Comment by OrangeOwlSolutions** [comment]
Thank you for notifying the issue. We have just solved it. Thanks again.
