### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hwinkler** [OrangeOwlSolutions/CUDA-Utilities#4]
Followed the link here from 
http://stackoverflow.com/questions/24368197/getting-cuda-thrust-to-use-a-cuda-stream-of-your-choice

thanks for publishing these utils. any chance you could designate an open-source license for them? no license means we have no right to use them in code. thanks again.

**Comment by OrangeOwlSolutions** [comment]
Hugh,
thank you very much for your interest into the CUDA Utilities library. The software is distributed under the GNU LGPL3 license. We have added the license indication, as requested.
The OrangeOwlSolutions Team.
